services:
  - type: web
    name: stock-chart-analyzer
    env: python
    plan: free
    buildCommand: pip install -r requirements_enhanced.txt
    startCommand: uvicorn main_enhanced:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LOG_LEVEL
        value: INFO
      - key: PIP_VERSION
        value: "23.3.1"
    # Ensure Python environment is used
    dockerfilePath: ""
    dockerContext: ""
